# Generated by Django 4.2.1 on 2023-05-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Teacher'), (2, 'Student')], null=True),
        ),
    ]
