# Generated by Django 4.2.1 on 2023-05-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='father_name',
            field=models.CharField(null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='second_name',
            field=models.CharField(null=True, verbose_name='Имя'),
        ),
    ]
