# Generated by Django 4.2.1 on 2023-05-28 16:16

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_student_teacher_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(verbose_name='first name')),
                ('second_name', models.CharField(verbose_name='second name')),
                ('father_name', models.CharField(verbose_name='father name')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='person_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.fields.CharField, to='authentication.personinfo'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='person_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.fields.CharField, to='authentication.personinfo'),
        ),
    ]
