# Generated by Django 4.2.1 on 2023-05-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_personinfo_student_teacher_student_person_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
    ]
