# Generated by Django 4.2.1 on 2023-05-28 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_personinfo_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student', verbose_name='student')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Название')),
                ('studenttopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.studenttopic')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='topics',
            field=models.ManyToManyField(through='authentication.StudentTopic', to='authentication.topic'),
        ),
        migrations.AddConstraint(
            model_name='studenttopic',
            constraint=models.UniqueConstraint(fields=('topic', 'student'), name='topic_student_idx'),
        ),
    ]
