# Generated by Django 4.2.1 on 2023-05-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_studenttopic_message_student_topics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(verbose_name='Сообщение'),
        ),
    ]
