# Generated by Django 4.2.1 on 2023-05-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_studenttopic_options_remove_message_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='upload',
            field=models.FileField(null=True, upload_to='test'),
        ),
    ]
