# Generated by Django 4.2.1 on 2023-05-28 18:56

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_message_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='topic',
            name='upload',
            field=models.FileField(null=True, upload_to=authentication.models.Topic.user_directory_path),
        ),
    ]
