# Generated by Django 4.2.1 on 2023-05-29 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_topic_description_topic_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinfo',
            name='number_of_contract',
            field=models.CharField(null=True, verbose_name='Номер Договора'),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='passport_serial_with_number',
            field=models.CharField(null=True, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='region',
            field=models.CharField(null=True, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='school',
            field=models.CharField(null=True, verbose_name='Школа'),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='study_major',
            field=models.CharField(null=True, verbose_name='Направление обучения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='studenttopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='authentication.studenttopic'),
        ),
        migrations.AlterField(
            model_name='student',
            name='topics',
            field=models.ManyToManyField(related_name='students', through='authentication.StudentTopic', to='authentication.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='authentication.teacher'),
        ),
    ]
