# Generated by Django 4.2.1 on 2023-05-29 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_personinfo_year_in_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personinfo',
            old_name='year_in_school',
            new_name='language',
        ),
    ]
