# Generated by Django 4.2.1 on 2023-06-08 14:48

import authentication.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_rename_year_in_school_personinfo_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.FileField(null=True, upload_to=authentication.models.Billing.upload_receipt_folder)),
                ('create_at', models.DateField(default=datetime.date(2023, 6, 8))),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
            ],
        ),
    ]
