# Generated by Django 4.2.1 on 2023-06-08 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='billing',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='authentication.billing'),
            preserve_default=False,
        ),
    ]
