# Generated by Django 4.2.1 on 2023-06-08 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_alter_student_billing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billing',
            options={'verbose_name': 'Чеки оплаты', 'verbose_name_plural': 'Чеки оплаты'},
        ),
        migrations.AlterField(
            model_name='student',
            name='billing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.billing'),
        ),
    ]
