# Generated by Django 4.2.1 on 2023-06-08 16:55

import authentication.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_alter_billing_options_alter_student_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='course_name',
            field=models.CharField(null=True, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='create_at',
            field=models.DateField(default=datetime.date(2023, 6, 8), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='receipt',
            field=models.FileField(null=True, upload_to=authentication.models.Billing.upload_receipt_folder, verbose_name='Чек'),
        ),
    ]
